### ISSUE TITLE
Cannot reproduce finetuning result on Audioset-20k

### ISSUE THREAD

**Issue by kxgong** [facebookresearch/AudioMAE#23]
Thanks for the great work.

When I reproduce the finetuning result on Audioset-20k, the best I can get is 35.4 while the reported result is 37.0.

I use the example script in this repo. 

In addition, I vary the value of the learning rate from [-1e-4,  -1e-2] and the value of batch size from [4, 64], the best result remains 35.4.

Could you provide some ideas to have better results?

**Comment by chandlerbing65nm** [comment]
@kxgong Hi, I'm also trying to run finetuning on this code. I encountered an error related to the data `Audioset-20k` having different tensor sizes, did you have the same error before?

```python
Traceback (most recent call last):
  File "main_finetune_as.py", line 519, in <module>
    main(args)
  File "main_finetune_as.py", line 475, in main
    train_stats = train_one_epoch(
  File "/home/timm/chandler/Experiments/AudioMAE/engine_finetune_as.py", line 45, in train_one_epoch
    for data_iter_step, (samples, targets, _vids) in enumerate(metric_logger.log_every(data_loader, print_freq, header)):
  File "/home/timm/chandler/Experiments/AudioMAE/util/misc.py", line 144, in log_every
    for obj in iterable:
  File "/home/timm/miniconda3/envs/mae/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/timm/miniconda3/envs/mae/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/timm/miniconda3/envs/mae/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/timm/miniconda3/envs/mae/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/timm/miniconda3/envs/mae/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/timm/miniconda3/envs/mae/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/timm/miniconda3/envs/mae/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/timm/chandler/Experiments/AudioMAE/dataset.py", line 263, in __getitem__
    fbank, mix_lambda = self._wav2fbank(datum['wav'], mix_datum['wav'])  
  File "/home/timm/chandler/Experiments/AudioMAE/dataset.py", line 198, in _wav2fbank
    temp_wav[0, 0:waveform2.shape[1]] = waveform2
RuntimeError: expand(torch.FloatTensor{[2, 423188]}, size=[423188]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
```

**Comment by shanmukasadhu** [comment]
I was wondering what learning rate and batch size you were able to use to get that 35.4 metric?
